config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#index"
  resources :recipes, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create 
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :text, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :cream, presence: true
  validates :procedure, presence: true  
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, presence: true
  validates :profession, presence: true
  validates :size, presence: true

  has_many :recipes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :profession, :size])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to recipe_path(@comment.recipe)
    else
      @recipe = @comment.recipe
      @comments = @recipe.comments
      render "recipes/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, recipe_id: params[:recipe_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, except: [:index, :new, :create]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.includes(:user)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end



  private
  def recipe_params
    params.require(:recipe).permit(:title, :cream, :procedure, :image).merge(user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @recipe.user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ShoesRecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("IMG_8927 2.jpg", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Recipe", new_recipe_path, class: :nav__btn %>
            </div> 
            <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © SHOES RECIPE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: recipe, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "靴の名前" %><br />
    <%= f.text_field :title, id:"recipe_title" %>
  </div>

  <div class="field">
    <%= f.label :cream, "使った道具" %><br />
    <%= f.text_area :cream, class: :form__text, id:"recipe_cream" %>
  </div>

  <div class="field">
    <%= f.label :procedure, "手順" %><br />
    <%= f.text_area :procedure, class: :form__text, id:"recipe_procedure" %>
  </div>

  <div class="field">
    <%= f.label :image, "レシピの画像" %><br />
    <%= f.file_field :image, id:"recipe_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="card">
  <%= link_to image_tag(recipe.image, class: :card__img ), recipe_path(recipe) %>
  <div class="card__body">
    <%= link_to recipe.title, recipe_path(recipe), class: :card__title%>
    <p class="card__summary">
      <%= recipe.cream %>
    </p>
    <%= link_to "by #{recipe.user.name}", user_path(recipe.user), class: :card__user %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">レシピ編集</h2>
      <%= render partial: "form", locals: { recipe: @recipe } %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<main class="main">
  <div class="inner">
  <% if user_signed_in? %>
      <div class="greeting"> 
         こんにちは、 
         <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link%>
      </div> 
      <% end %>
    <div class="card__wrapper">
      <%= render partial: 'recipe', collection: @recipes %>
    </div>
  </div>
</main>

app/views/recipes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規レシピ投稿</h2>
        <%= render partial: "form", locals: { recipe: @recipe } %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="recipe__wrapper">
      <p class="recipe__hedding">
        <%= @recipe.title %>
      </p>
      <%= link_to "by #{@recipe.user.name}", user_path(@recipe.user), class: :recipe__user %>
      <% if current_user == @recipe.user%>
        <div class="recipe__manage">
          <%= link_to "編集する", edit_recipe_path(@recipe), class: :recipe__btn %>
          <%= link_to "削除する", recipe_path(@recipe), method: :delete,  class: :recipe__btn %>
        </div>
        <% end %>
      <div class="recipe__image">
        <%= image_tag @recipe.image %>
      </div>
      <div class="recipe__body">
        <div class="recipe__detail">
          <p class="detail__title">使った道具</p>
          <p class="detail__message">
            <%= @recipe.cream %>
          </p>
        </div>
        <div class="recipe__detail">
          <p class="detail__title">手入れの手順</p>
          <p class="detail__message">
            <%= @recipe.procedure %>
          </p>
        </div>
      </div>
      <div class="recipe__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@recipe, @comment], local: true do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.text%>
              <%= link_to "（#{comment.user.name}）", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
          <ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">職業</th>
            <td class="table__col2"><%= @user.profession %></td>
          </tr>
          <tr>
            <th class="table__col1">足のサイズ</th>
            <td class="table__col2"><%= @user.size %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのレシピ"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'recipes/recipe', collection: @user.recipes %>
      </div>
    </div>
  </div>
</div>